### ISSUE TITLE
Implement /get_limit Endpoint

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/vault#33]
## Description

We need to implement the `/get_limit` endpoint in the Vault backend. This endpoint is responsible for retrieving the account spending limit.

## Details

- **Method:** GET
- **Path:** /get_limit
- **Summary:** Get the account spending limit.

### Response:

- **Status Code:** 200
- **Description:** Account current spending limit
- **Content Type:** application/json
- **Body:**

```json
{
  "limit": "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD"
}
```

### Notes:

The spending limit is represented in hexadecimal format.

### Example

```typescript
// Import necessary modules
import fastify from 'fastify';

// Create Fastify instance
const app = fastify({ logger: true });

// Define the get_limit endpoint
app.get('/get_limit', async (request, reply) => {
    try {
        // Logic to retrieve the spending limit goes here

        // Return the spending limit
        return { limit: "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD" };
    } catch (error) {
        // Handle errors
        console.error('Error while retrieving spending limit:', error);
        return reply.status(500).send({ error: 'Internal Server Error' });
    }
});
```

## Tasks:

- [ ] Implement the `/get_limit` endpoint.

**Comment by LucasLvy** [comment]
yes please do

**Comment by Gift-Naomi** [comment]
Hello Lucas, I've set up the project locally on my machine, but I need clarification on the database schema I am to work with.
I've checked the current database schema and non appeared to have a limit field.

**Comment by LucasLvy** [comment]
This has to be indexed by apibara it will get added later, can you create a mock table that has address as primary key and limit ? Add a todo somewhere to index that from apibara and I’ll create an issue (or if you know how to work with apibara you can directly do it)

**Comment by Gift-Naomi** [comment]
Alright, I will create a mock table with the fields you specified.
I'm not familiar with apibara, But I'll check it out .

**Comment by Gift-Naomi** [comment]
Hi @LucasLvy I created a PR #61.
It's ready for review.
