### ISSUE TITLE
Implement /get_current_expense Endpoint

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/vault#34]
## Description

We need to implement the `/get_current_expense` endpoint in the Vault backend. This endpoint is responsible for retrieving the cumulated expensed amount on the 7 previous days for a specific account.

## Details

- **Method:** GET
- **Path:** /get_current_expense
- **Summary:** Get the cumulated expensed amount on the 7 previous days.

### Request Parameters:

- **address:** The Ethereum address for which the expensed amount is to be retrieved.

### Response:

- **Status Code:** 200
- **Description:** Cumulated expensed amount on the 7 previous days
- **Content Type:** application/json
- **Body:**

```json
{
  "cumulated_expense": "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD"
}
```

### Notes:

The cumulated expensed amount is represented in hexadecimal format.

### Example

```typescript
// Import necessary modules
import fastify from 'fastify';

// Create Fastify instance
const app = fastify({ logger: true });

// Define the get_current_expense endpoint
app.get('/get_current_expense', async (request, reply) => {
    try {
        // Logic to retrieve the cumulated expense amount goes here

        // Return the cumulated expense amount
        return { cumulated_expense: "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD" };
    } catch (error) {
        // Handle errors
        console.error('Error while retrieving cumulated expense amount:', error);
        return reply.status(500).send({ error: 'Internal Server Error' });
    }
});
```

## Tasks:

- [ ] Implement the `/get_current_expense` endpoint.

**Comment by kateberryd** [comment]
Hi @LucasLvy I'll like to work on this

**Comment by MhdSadd** [comment]
Good day @LucasLvy can I pick this up

**Comment by LucasLvy** [comment]
@raizo07 are you already working on this ?

**Comment by raizo07** [comment]
@LucasLvy Yes I am working on it already.
