### ISSUE TITLE
Implement /generate_claim_link Endpoint

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/vault#40]
## Description

We need to implement the `/generate_claim_link` endpoint in the Vault backend. This endpoint is responsible for generating a link that will allow anyone to claim a specific amount of USD.

## Details

- **Method:** POST
- **Path:** /generate_claim_link
- **Summary:** Generate a link that will allow anyone to claim a specific amount of USD.

### Request Body:

```json
{
    "amount": 100,
    "address": "0x0123456789abcdefABCDEF0123456789abcdefABCDEF0123456789abcdefABCD"
}
```

- **amount:** An integer representing the amount of USD to claim.
- **address:** A string representing the recipient's address.

### Response:

- **Status Code:** 200
- **Description:** Claim link generated successfully
- **Content Type:** application/json
- **Body:**

```json
"https://example.com/claim/1234567890"
```

### Notes:

- The claim link is a URI that can be accessed to claim the specified amount of USD.

## Example

```ts
// Import necessary modules
import fastify from 'fastify';

// Create Fastify instance
const app = fastify({ logger: true });

// Define the generate_claim_link endpoint
app.post('/generate_claim_link', async (request, reply) => {
    try {
        const { amount, address } = request.body;

        // Perform logic to generate claim link based on the provided amount and address
        const link = await generateClaimLink(amount, address);

        // Return the generated claim link
        return { link };
    } catch (error) {
        // Handle errors
        console.error('Error generating claim link:', error);
        return reply.status(500).send({ error: 'Internal Server Error' });
    }
});

// Start the server
app.listen(3000, '0.0.0.0', (err, address) => {
    if (err) throw err;
    console.log(`Server listening on ${address}`);
});

// Dummy function to generate claim link (replace with actual logic)
async function generateClaimLink(amount: number, address: string): Promise<string> {
    // Dummy implementation
    return "https://example.com/claim?token=abc123";
}
```

## Tasks:

- [ ] Implement the `/generate_claim_link` endpoint.

**Comment by EjembiEmmanuel** [comment]
@LucasLvy can I work on this?

**Comment by MhdSadd** [comment]
Good day @LucasLvy can I pick this up?

**Comment by LucasLvy** [comment]
Hey no i'll do this one should've assigned it to me sorry
